### ISSUE TITLE
Cannot open channel with less than 300.000 sat

### ISSUE THREAD

**Issue by gustavonalle** [btcontract/lnwallet#100]
Not sure if this is an issue of lnd or this wallet,  but every channel I try to open requires a minimum of 300.000 sat as funding. I have a lnd node and the minimum amount to accept channels is 20.000 sat, still the wallet shows "min capacity: 300.000" when trying to open a channel to my lnd node.

**Comment by btcontract** [comment]
Yes, 300k SAT is a limit imposed by BLW. Technical reasons for this are outlined here: https://github.com/btcontract/lnwallet/issues/52. 

Actually wallet parameters have changed since then so it should be possible to lower it to 150k now but I've decided to leave it as is because extra small channels may be remotely force-closed because of on-chain fee spikes.

**Comment by btcontract** [comment]
Closing this for now, feel free to reopen if any questions still remain.
