### ISSUE TITLE
Ammount is too large/too small while paying

### ISSUE THREAD

**Issue by berbant** [btcontract/lnwallet#120]
My wallet has 1000000 sat
The channel says:
  capacity: 2000000 sat
  can send: -20000 sat
When I send any amount of satoshi (QR Code -> Pay) I get the message "Amount is too large"
I just tried to send 1 sat and got the message "Amount is too small".
What am I doing wrong?

**Comment by btcontract** [comment]
As far as I understand `1 000 000 SAT` is your on-chain balance (the one not in a channel) and also you have an incoming channel with capacity of `2 000 000 SAT`, probably ordered at Bitrefill?

`can send: -20000 sat` indicates that this is a fresh _incoming_ channel. What this means is that for this channel all the funds are currently on peer's side (since they have used their money to open it) so at the moment this channel can only be used on your side for receiving, not for sending.

`-20000 sat` is an unspendable reserve so if you want to send, say, `10 000 SAT` off-chain then first you need to receive at least `30 000 SAT` into that channel to cover reserve and desired amount.

Another option would be to use `1 000 000 SAT` you currently have on-chain to open a second, _outgoing_ channel with a peer of your choice (Bitcoin button -> "Open new channel" -> Select peer). With _outgoing_ channel situation is reversed: all the funds are on your side at start so you can only use to to send funds first.

Additional info can be found here: [Receiving Lightning funds](https://lightning-wallet.com/using-lightning-wallet#receiving-lightning-funds)

**Comment by berbant** [comment]
Thank you for the full answer to the question from newbie. The option two is working.
But I couldn't receive satoshi into the "fresh" Bitrefill channel. Did I understand correctly that in this case I have to close it and open again?

**Comment by btcontract** [comment]
No, don't close it, just wait a bit. Sometimes restarting an app also helps (this is a small bug, will be fixed soon).

**Comment by btcontract** [comment]
Just to make sure we're on a same page: when you try to receive, are there any warnings like "receiving is not enabled yet" or does wallet allow you to create a payment request but you can't fulfill it from another lightning wallet?

**Comment by berbant** [comment]
Well I have two channells. One of them "can send" 500K sat. The other "can receive" 2000K satoshi. Also I have 500K on-chain satoshi. I do the lighting network invoice (Bitcoin button -> Receive funds -> Lighting Payment-> 5000 sat. -> copy). And then I do - Bitcoin button -> Send funds -> Paste... Lighting Payment Request and I see the warning "Failed because payments to yourself aren't allowed". And also I won 10 sat. playing Lightning Roulette and I manage to transfer them into the 2000K channel.

**Comment by btcontract** [comment]
Ah I see, sending to self is indeed restricted for now. I plan to enable it in future but it requires some changes and is overall not an urgent feature. Meanwhile you can test receiving from here: https://www.coinpanic.com/Lightning/CommunityJar

**Comment by berbant** [comment]
Thank you for the link and the responses to questions.
