### ISSUE TITLE
how to find full LN node ID?

### ISSUE THREAD

**Issue by mattnook** [btcontract/lnwallet#136]
Hi, I am trying to open a channel to my Bitcoin Lightning Wallet. I am wondering how to get my FULL node ID. Right now the "Share Node ID" only gives me the public key, which I can't find on the network from searching 1ML.com

What is the full address of my LN Node ID?

**Comment by btcontract** [comment]
There is no such thing as full/short node id, the one from "Share Node ID" menu is as full as it gets.

The reason your phone node is not seen on 1ML is because mobile wallets do not advertize themselves and only open private channels, so they are not present on a public graph, by design.

It's still possible to open an incoming channel into mobile wallet by doing the following:

1. Establish a connection to your desktop LN node from BLW by either selecting your node in "Open channel" page, or by scanning a node QR from wallet.

2. Once connected you'll see a special channel opening page and a funding popup in BLW as it tries to open an outgoing channel, either dismiss it or do nothing, but do stay on that page to maintain a connection.

3. While connected, issue a channel opening command from your desktop LN node using wallet ID obtained from menu, the trick is BLW should be connected when a command is issued. Also offered incoming channel must be private, BLW will ignore public offerings.
