### ISSUE TITLE
Sending payment caused force closure.

### ISSUE THREAD

**Issue by deafboy** [btcontract/lnwallet#14]
As soon as I scanned a QR code the channel has been unilaterally closed.
https://imgur.com/a/TNtgT

Both wallets had a common peer (cloudy2) but there there is nothing unusual around that time in it's logfile, so I assume the closure was initiated by the lnwallet.
I'd love to provide more details but I have no idea how.

**Comment by btcontract** [comment]
> I assume the closure was initiated by the lnwallet

Yes it was since a refunding transaction is encumbered in a 144 block delay.

Were there any stuck outgoing payments with that peer? Under stuck I mean unfulfilled for days.
If not, can you just try to reproduce this once again? Meanwhile, I'll also try to open a channel to cloudy2 and make some payments.

**Comment by btcontract** [comment]
Successfully opened a channel and made a few payments, no issues so far.

**Comment by bitcoinuser** [comment]
Today, I had the same problem of @deafboy. But I don't remember in what channel I was connected and what I was trying to pay.

**Comment by btcontract** [comment]
If this is some kind of internal crash then lnwallet will print detailed error contents on a screen and copy them to a clipboard at the same time. So if this happens againg please just paste a report.

**Comment by deafboy** [comment]
I'll try to capture the error next time. Meanwhile I've discovered this: https://github.com/ACINQ/eclair/issues/313
