### ISSUE TITLE
Dust limit too large when trying Turbo channel

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnwallet#140]
Problem:

When attempting to accept a Turbo channel, "Dust limit too high" message appears for a while and opening fails. The message specifies that the dust limit is 2730, while max is 1000.

I have set dust limit to 546, yet the problem persists. It's unclear whether BLW is rejecting the channel or Eclair. I suppose it's Eclair.

**Comment by btcontract** [comment]
This is a known issue which used to affect channels of low capacity (below 273 000 SAT), but it was fixed in last 0.3-130 update. I guess you're using an outdated BLW version, updating it should fix an issue.

What is going on: both Eclair and BLW provide their own dust limits, Eclair's is 546 SAT by default while BLW's was 2730 SAT (546 SAT now). When opening a channel there's a so called unspendable reserve which can not be lower than 1% of channel capacity AND can not be lower than dust limit. So when proposed channel capacity was below 273 000 SAT Eclair was rejecting it because BLW's dust was higher than minimal allowed reserve.

With latest update minimal incoming channel capacity is 54 600 SAT.

**Comment by Kixunil** [comment]
Ah, thanks, that helped! Now I'm getting "They are funder and cannot afford fees message".

**Comment by btcontract** [comment]
Probably remote funder tries to push too much money on BLW side.
An example: total channel capacity is 100 000 SAT and remote funder pushes 95 000 on BLW side. Current on-chain feerates would require 6000 SAT for a commitment transaction. Fees are paid by remote funder and they only left 5000 SAT to themselves, so channel gets rejected.

**Comment by Kixunil** [comment]
Figured it out - local amount was equal to push. I raised it by 20000 sats and it works. It'd be helpful if you know how to exactly calculate minimum value instead of guessing.

**Comment by Kixunil** [comment]
LOL, GitHub lag, thanks! :)
