### ISSUE TITLE
No support for creating 0 satoshi invoices

### ISSUE THREAD

**Issue by baebb** [btcontract/lnwallet#143]
0 sat invoices are useful because it allows the payer of the invoice to set the amount of satoshi they will send to the invoice creator

**Comment by btcontract** [comment]
Sadly this specific type of invoice has vulnerabilities (https://github.com/breez/breezmobile/issues/110), so won't implement.

**Comment by btcontract** [comment]
Actually it turns out there is no vulnerability if implemented properly.

**Comment by baebb** [comment]
That's great! I rely on 0 sat invoices heavily for www.lightning.gifts

**Comment by btcontract** [comment]
After some further research it turned out vulnerability is there, the details are at https://github.com/ottosuess/ottosuess.github.io/blob/master/zero-amount-payments.md.

Amount-less invoice functionality will be replaced by spontaneous payments in a future, for now I'd advise not to use them as given a history of previously found LN exploits it's just a matter of time before someone starts abusing this.

**Comment by baebb** [comment]
@btcontract thanks for the follow up. I'm removing it too
