### ISSUE TITLE
Channel name got corrupt

### ISSUE THREAD

**Issue by schildbach** [btcontract/lnwallet#152]
I believe I opened a channel to `ln1.satoshilabs.com` on July 17. I used it to pay many times without serious issues.

About two weeks ago, I noticed the channel is offline for a since a long time. I also noticed that the name now is `ln1.satoshilabs.co`. Had I fallen afoul to a SatoshiLabs impostor when I opened the channel?

But then, I noticed the token usage log says: 'Saved an encrypted backup for a channel with «ln1.satoshilabs.com». So it looks like I got the name right but the app somehow corrupted the name, which would also explain the continuous downtime of the channel.

I'm now trying to refund the channel.

The currently installed version is 0.3-138.

**Comment by btcontract** [comment]
> About two weeks ago, I noticed the channel is offline for a since a long time. I also noticed that the name now is ln1.satoshilabs.co.

Yes, that's a known issue in a sense that `ln1.satoshilabs.com` has become unresponsive quite some time ago. It seems to be online but drops connections, probably due to some bug.

> Had I fallen afoul to a SatoshiLabs impostor when I opened the channel?

Not in this case, it was purely a UI decision of mine to limit alias length because they may get quite long and break indentations on channel cards. That said, alias indeed should not be relied upon as it can be set to anything and can be changed later by remote node owner. What always remains the same is `nodeId` (first 15 characters are shown by BLW). Opening a channel with impostor due to same alias is possible but is not a serious problem since channel can always be closed without permission.

> I'm now trying to refund the channel.

Is channel in SHUTDOWN state? If yes, you need to close it for the second time to initiate a local-force-close. What's going on here: if user attempts to close a channel while it's offline there are only two options: start force-close right now or wait until it becomes online and then proceed with cooperative close. BLW makes a second optimistic choice and awaits, which sometimes can fall short like this.

**Comment by schildbach** [comment]
Thanks for the explanation. I think if channel names are limited in the UI, it would have helped if they were ellipsized ("ln1.satoshilabs.co…").

The force close seems to be progressing fine.

**Comment by btcontract** [comment]
> I think if channel names are limited in the UI, it would have helped if they were ellipsized ("ln1.satoshilabs.co…")

yes, this makes sense, thanks for suggestion.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/578490b9b57d64cf7820eb554c82f989b44bdd75
