### ISSUE TITLE
LN payments keep failing out of box

### ISSUE THREAD

**Issue by apavel3458** [btcontract/lnwallet#155]
Hi there,
I just downloaded BLW, added funds, opened a channel to OpenNode.com, and tried to make a payment to Bitrefill 
![image](https://user-images.githubusercontent.com/27737921/69094604-b1698280-0a1e-11ea-8751-118f5d1a03d8.png)

Then I tried to pay:
![Screenshot_20191118-161626](https://user-images.githubusercontent.com/27737921/69094699-deb63080-0a1e-11ea-99f4-e1216eccabe9.png)
![Screenshot_20191118-161617](https://user-images.githubusercontent.com/27737921/69094707-e07ff400-0a1e-11ea-89fd-e32480b048df.png)

Does anyone know why I can't pay.  It keeps saying "Lightning payment failed and refunded".  
I didn't change any settings or anything on the app.  Im using google phone pixel 3.  I initially thought it was VPN, but after turning off VPN and tried various networks, It still has the same issue.

Thanks!

**Comment by btcontract** [comment]
these are different issues: the first one (reddit screenshot) is that app was waiting for on-chain wallet to become online to start an LN payment, but now it is actually online and gets a payment failed.

Can you try the following: attempt another payment, if it fails again tap on it, then tap "share debug info" in popup window, then paste it here?

**Comment by apavel3458** [comment]
Hi there, thanks for the reply.  
I don't see "share debug info".  When I tap the failed transaction it gives me the pop-up window you see in that screenshot.  If i click "share payment request", it gives me this:
lnbc49u1pwax9cspp55ra0ujckwqecwjmrry48n6kzw9re8yfvyt2wnqdp5ep3s2442qgsdz2gf5hgun9ve5kcmpqvyenxdmrxq6xvtfexymkztf5v4jryttz8q6xytt9xf3kzc3jxeskve3evyfppj9lkg9705uvm9sxmwl2lrzc3srury4v3hxqrp9s4w7gjf3t8g27l3rhswgd6m4utjfctlp9erzqfghtzyxvfr79g2wz5cquau698jxyd8hgumn3mn4mkpc2m4pgaq9edeg0u6jh8v97t9cqq4mh78

**Comment by btcontract** [comment]
Yes, right, it won't show debug info after an app is restarted since that data is not stored in a database. You'd need to try out another payment (order a thing at bitrefill once again), and then debug info will be available.

**Comment by apavel3458** [comment]
It doesn't give me the option to share bug report.  Attached is the other attempt:
![Screenshot_20191118-171919](https://user-images.githubusercontent.com/27737921/69098989-b4b53c00-0a27-11ea-8256-5d95633adda2.png)
![Screenshot_20191118-171924](https://user-images.githubusercontent.com/27737921/69098994-b5e66900-0a27-11ea-8e35-139d0c67e25d.png)

**Comment by btcontract** [comment]
I see, no debug info at all in this case means there were no payment attempt, probably because no routes were found. This is really strange given that OpenNode is well connected.

To make sure this is not related to receiver (Bitrefill), can you try to fulfill this 500 SAT invoice to me? (I'll send back if successful).

![photo_2019-11-19_00-27-37](https://user-images.githubusercontent.com/9870980/69099444-6de53780-0a63-11ea-8081-5ef0a005d871.jpg)
lnbc5u1pwaxx4nrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7zfgw5qqwngqqqqqqqlgqqqqqeqqjqrzjqvww9ygka2m7m4npfr63d8clkev0443tm3gfzgs6hz2luhfkmvqtyzfvtsqq8zsqqyqqqqlgqqqqthqqrcdqqcqzyspp5hcwzd9zxml0txlfr9kw0qrn0q3ug5936e5eqjn5a7dajxhw7vl7qxqyz5vpk0wdzs2q90uvq6jnc8mqktg5ke7aygstj57d49pjjljk32uyu49quwz87lj5vcgncw254mxrfda77gd2pu2q52z2wrwq7hhq5xx3lhsqesqtwn

**Comment by apavel3458** [comment]
Tried, same issue:

![Screenshot_20191118-173404](https://user-images.githubusercontent.com/27737921/69099822-b97aef80-0a29-11ea-9ba9-47f35999fcc4.png)
![Screenshot_20191118-173412](https://user-images.githubusercontent.com/27737921/69099825-baac1c80-0a29-11ea-87cf-1bef0d925458.png)

**Comment by btcontract** [comment]
Okay, can you show a channel detail page? I'll use that info to connect to the same node and try to make some payments from it. I know it's OpenNode but it actually may not belong to them as anyone is free to provide any alias for their nodes.

**Comment by apavel3458** [comment]
![Screenshot_20191118-173939](https://user-images.githubusercontent.com/27737921/69100129-7ec58700-0a2a-11ea-94f1-799b62efc187.png)

**Comment by btcontract** [comment]
Thanks, getting a channel open. This may take some time but I'll definitely get back to you after trying to pay through it.

**Comment by apavel3458** [comment]
ok thanks!

**Comment by btcontract** [comment]
I've found out why this is happening, it's a bit technical but anyway:

1. when selecting a payment route there is a `cltvDelta` parameter for each hop which is measured in blocks, a total `cltvDelta` for an entire route basically means "for how long an LN payment can be in-flight before getting failed, measured in blocks".

2. BLW has a max `cltvDelta` set to `1008` blocks which means all routes above that will be instantly discarded. It turns out this value has been increased to `2016` in LN spec recently but BLW still has an old value.

3. OpenNode has a `cltvDelta` value set to `1000` blocks for all its channels so combined with next hops __all__ routes where OpenNode hop is present are discarded by BLW. And since OpenNode is the only node you have a channel with it basically blocks your ability to pay anywhere through it.

The solution is I'll update a max value to `2016` and issue an update, one updated you'll be able to pay. This will probably take a few days to get through.

**Comment by btcontract** [comment]
A `0.4-141` update is out there, I assume it should fix your issue. Feel free to reopen if issue persists even after an update.
