### ISSUE TITLE
LN payment sent twice for same invoice, only shows once in tx list

### ISSUE THREAD

**Issue by nanotube** [btcontract/lnwallet#17]
I was trying to pay an LN invoice for 10k sats issued from a Breez wallet. 
When I paid, BLW said transaction failed, and offered to 'retry'.
But in Breez, after that first try, the 10k sats showed up, and i was even able to spend some of them.
I restarted BLW, transaction still showed as failed. so I clicked 'retry'. 
It then said 'successful', seemed like it updated my balance (i'm not sure actually, since I didn't note exactly the number of sats i had before this whole thing happened). And another 10k sats showed up in my Breez wallet.
But in BLW, the transaction list only shows the one 10ksat transaction. 
I'll be glad to provide debug info or whatever other info needed, just lmk.

**Comment by btcontract** [comment]
Sorry for late response, did not notice this earlier.

What happened here is some node along a payment route failed to deliver preimage back to BLW but instead failed a first payment which is actually good for you the payer since you've gained 10k sat in Breez but did not lose them in BLW.

Faulty relay node along a payment route is a bearer of costs here. This does look a lot like this issue: https://github.com/lightningnetwork/lnd/issues/2865.

**Comment by nanotube** [comment]
Ah, thank you for following up. Based on that LND issue, they say it's fixed as of 11days ago, so... hopefully that fixes it. If i notice something like this again I'll post. 
And thank you for making BLW, my favorite mobile wallet!
