### ISSUE TITLE
after upgrade, lost wallet data and can not recovery

### ISSUE THREAD

**Issue by wymcmh** [btcontract/lnwallet#40]
I upgrde the wallet app today, and found the original information was lost.
Then, I use mnemonic phrase to recover, but the wallet is empty!

**Comment by btcontract** [comment]
This is expected as wallet format was changed from legacy to native segwit addresses. 

I understand this feels worrisome to say the least but this is a one time event which was not even planned earlier but had to be carried out because legacy wallet was buggy and slow.

Feel free to post your testnet segwit address here if you have problems refilling the wallet (since no testnet faucet supports this type of addresses yet).
