### ISSUE TITLE
Cannot open channel

### ISSUE THREAD

**Issue by suvayu** [btcontract/lnwallet#41]
I cannot open a channel.  I have funded the wallet with 500k testnet satoshis, but when I try to open a channel, it fails with either "data loss protection is not provided by this peer" or "could not connect to remote peer at ...".

I'm on Android 8

**Comment by btcontract** [comment]
This is normal. There is an optional feature called `data-loss-protect`, when opening a channel with a node which supports it there is an easy way to get the money back from lost channel in case of emergencies like phone loss. 

Bitcoin + Lightning Wallet requires this feature to be supported by peer but so far very few nodes support it on testnet and mainnet. Here is a node which definitely supports this feature: https://explorer.acinq.co/n/03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 (ACINQ endurance node)

"could not connect to remote peer at ..." means remote peer is offline. Offline peers are present in a list because there is no easy way to know if they're available before attempting to open a channel.

**Comment by suvayu** [comment]
Thanks a lot for your response.  I was able to connect to the node suggested by you.  Maybe the UI could be improved to show if a node supports `data-loss-protect`, say a filtering option where this could be toggled?

**Comment by btcontract** [comment]
No, same issue as with offline nodes: can't know that until try to connect and negotiate node features.

**Comment by btcontract** [comment]
lol, I've replied to you on google play referencing this ticket and oly later realized it was your review

**Comment by suvayu** [comment]
:grin: I submit the review before I realised I could create an issue here.  I'll update the review to reflect our discussion above.

About the nodes, maybe for now you can add a way for the user to bookmark/label a node they know to support a certain feature.  That would be really helpful.

For the long term though, the nodes need to "advertise" supported features. But that probably requires a change at the protocol level, maybe Lightning v2. I'll open a separate issue for the other stuff I spotted.
