### ISSUE TITLE
Usability: funding a channel up to a fraction of the capacity

### ISSUE THREAD

**Issue by suvayu** [btcontract/lnwallet#42]
Currently when a channel is opened, it is funded to its full capacity. I wanted to try and see how I can receive payments using lightning. Which meant first I had to spend enough so that I can receive!  Which is a bit backwards if you ask me :smile:

So my feature request is to be able to choose the capacity and up to what fraction of the capacity I want to fund it.  Without this, it would be hard to have microdonation addresses.

What do you think?

**Comment by btcontract** [comment]
Currently the only way to create a "partially funded" channel would be to open it regulary and push a portion of funds to a peer right away which is basically giving out money and is not exactly what you want.

Another theoretical idea are mutually funded channels where both parties deposit, say, 50% of sum. But there is no support for such operations on a protocol yet.

In general this is a rather fundamental limitation which along with other requirements (like the need to be online to receive LN funds) indeed makes my wallet a poor choice for small and frequent donations in particular.

Receive capability here is mainly intended for refilling of channel balance off-chain once it gets depleted instead of closing it and opening a new channel.

**Comment by suvayu** [comment]
Okay I understand.  I'll have to look for a different solution for microdonations.  For its other features, I quite like your wallet, thanks :smile:

**Comment by Pheromon** [comment]
For microdonations and very simple usage you can use Bitcoin Cash: with the hard fork planned in a few days the network will be able to handle millions of txs per days with negligible costs.

**Comment by suvayu** [comment]
@Pheromon, I'm not interested in holding BCH.

**Comment by earonesty** [comment]
Use CoinGate.   They will fund your receive only channel.... as donations come in.
