### ISSUE TITLE
Feature request: open channel with all on-chain funds.

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#44]
Often users will:
 - create a new wallet
 - send some BTC there
 - open a channel with ALL the BTC

Right now it's a bit a guess work how much satoshi to input to sweep all BTC funds.
If you don't enter a right value - funding tx will create TWO outputs (one for change) - this creates dust and makes tx more expensive.

Solution: add "Max" button in funding dialog that will send all BTC in one TX without creating any change output.

**Comment by btcontract** [comment]
Button is a good idea, makes it more obvious.

Just in case, this feature is supported already: just enter an exact on-chain balance and it will all go into channel without change and with fee correctly subtracted. But I admit the way it works now is somewhat cryptic.

Also: this will will only work if on-chain balance is less than or equal to 16 777 215 Satoshi since that value is current max channel capacity.

**Comment by btcontract** [comment]
Implemented in https://github.com/btcontract/lnwallet/commit/54252d7284b868a4a84906c256c1429641519b98, will be available in next update.
