### ISSUE TITLE
652 satoshi commission in LN

### ISSUE THREAD

**Issue by Perlover** [btcontract/lnwallet#48]
Hello!

I wrote in Russian my comment at Google Play
Now i describe questions here.

I have two my LND nodes. I decided to transfer 250000 satoshi from your wallet to my LND node. I connected to ACINQ node (recommended by your wallet), made channel. I created the invoice in my node and paid. Payment was OK but commission after paying was 652 satoshi through lightning. Present time same comisssion to be enough for bitcoin network but for LN it's very big.

https://www.dropbox.com/s/nyd5y461bm5nz6b/2018-06-04%2015.37.10.png?dl=0

    Signed payment request: lnbc2500u1pd320wgpp5jdwrjzww36xwna6d02x4qqjyhuu3c26h4dlv3ywhrve5lsmhcf5sdp06z0drqkshlgcp59s6zedpw7skhgtm597yrgczgz5v93zq5ccqzysxqrrssahyvd4s2y67wayyj2um26gmtuwqztxfkmstt98yqaqs6us5zsqm92epn93janfwcyxfe7kglhf6xwekrgjph3z750k555vwv68vch7spxw8nl3
    
    Payment preimage: d71e6c9403f6e64012ccdf8e04836200c9b503f917c53617f0e29230a645e519

I made other payment from other device 180000 by your wallet - comiission was 201 satoshi (through ACINQ)

I tested a payment from Eclair wallert -> my LND1 -> my LND2 and there was about 1 satoshi for same sum (250000).

Then i tested Eclair wallet -> ACINQ -> my LND1 - there was errors and payment was not successfull so i don't know comission for this way/

Second question about OP_RETURN data in fundng transaction

**Comment by btcontract** [comment]
First thing to note is fee model in LN is different from that of Bitcoin. On-chain transaction fee depends on tx size in bytes while in LN a fee is spread between routing nodes and depends on payment amount (to answer your other question: no, Olympus server takes no part in fee extraction, it's routing nodes only).

While `652 sat` may seem high when taken out of context it's actually within acceptable bounds since it's just 0.26% of payment sum. For example, Eclair has max acceptable fee threshold set to 3%, in my wallet fee acceptance rules are a bit more involved but generally converge to 4% of sum.

I have run a query for the payment request you've provided using ACINQ node as a starting point and here are annotated results:

```
route1: Vector(Hop(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f,578301334815703040,144,1000,1000,100), Hop(03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56,576361796323573761,144,1000,1000,1000)), 

route2: Vector(Hop(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f,578301334815703040,144,1000,1000,100), Hop(03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56,578384897729101824,144,1000,1000,2500)), 

route3: Vector(Hop(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f,575432709004787712,144,0,1000,100), Hop(021deedd44ba443c655d454b0d8f90791e12a0ffe07dbaa52016dc40f2d310c55c,575332653451378688,14,1000,1000,10), Hop(036403186a467144ea6aaf4d6e42f7544e91a78e0f8ebd8e38bd2054b953d82e3f,578484953218154497,144,1000,1000,1)), 

route4: Vector(Hop(03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f,575432709004787712,144,0,1000,100), Hop(021deedd44ba443c655d454b0d8f90791e12a0ffe07dbaa52016dc40f2d310c55c,575330454434217984,14,1000,1000,10), Hop(024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed,576348602185285633,144,1000,1000,2490))
```

Pay attention to the last `Hop` of route 2: `Hop(03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56,578384897729101824,144,1000,1000,2500)`, the last `2500` indicates a percent this node takes dependent on payment sum. The forumla in your case is `250000 * 2500 / 1000000` = `625 sat`, the node itself is none other than `mainnet.yalls.org` (https://1ml.com/node/03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56). This node has taken a majority of your payment's routing fee and there is no bug here. Perhaps this node charges a lot but eventually it's up to market to decide. Currently no other competing node can route your payment at a lower fee so this one has been chosen (route1 has been tried first and apparently failed).

**Comment by btcontract** [comment]
Now the OP_RETURN issue, the reason this exists is described in details here: https://groups.google.com/forum/#!topic/bitcoinj/SJpLgjowc1I

**Comment by btcontract** [comment]
Also, in upcoming app update it will be possible to extract a payment route ("share routing details" button) so you will be able to see which node took how much of the total fee:

 
![photo_2018-06-05_19-05-09](https://user-images.githubusercontent.com/9870980/40988314-6de294e8-68f3-11e8-9e3f-97121e476b87.jpg)

**Comment by bitcoinuser** [comment]
> Also, in upcoming app update it will be possible to extract a payment route ("share routing details" button) so you will be able to see which node took how much of the total fee:

I liked this idea.

**Comment by Perlover** [comment]
Thank you for detailed answer! I known many new things from your answer :)
