### ISSUE TITLE
Minimal limit of channel opening 300000 - why?

### ISSUE THREAD

**Issue by Perlover** [btcontract/lnwallet#52]
Hello!

My node has limit minimum 20000 satoshi. But when I try to make a channel with its BLW asks me minimal limit as 300000. Why? How can I change limit?

**Comment by btcontract** [comment]
It's due to a number of technical decisions I've made.
Suppose `Bob` wants to fund a payment channel with `Alice`. When opening a channel among other things `Bob` should specify two parameters:

- **Local dust limit**. All LN payments of sum below that limit won't be included in `Bob`'s commitment transactions. It should be at least `546 sat` but in my wallet a limit is set to `5460 sat`. The reason is I don't want users to end up with `600 - 5000 sat` outputs since I consider current low on-chain fees to be an anomaly and `600 - 5000 sat` outputs will become a burden if I'm correct: a fee required to spend such an output could become bigger than output amount itself.

- **Remote channel reserve**. `Alice` can't ever get a channel balance on her side to become below reserve value required by `Bob` so she never has a "nothing at stake" problem and always has at least that reserve to lose if she is tempted to publish a revoked commitment. Typical reserve value is 1% of channel capacity but my wallet sets to it 2% to further incentivize `Alice` to not break a channel.

The problem is there is a special protocol defined rule which `Alice` checks when proposed a channel by `Bob`, which is that `Alice` local channel reserve can't be less than `Bob` local dust limit (it gets a bit mind bending here).

So the issue this leads to is __if__ `Bob` says it's local dust is `5460 sat` and `Alice` remote reserve is 2% __then__ `Bob` can't open a channel of capacity less than `273 000 sat` (`5460 sat` is exactly 2% of `273 000 sat`).

One solution to this is to make either dust or reserve lower and another one is to make minimum channel limit relatively high which is the way I've taken. This decision is not set in stone though so if you or someone else think I'm wrong in my considerations then please let me know.
