### ISSUE TITLE
olympus server tokens - no decreasing

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#59]
I opened a channel with ACINQ few days ago and done around 60 transactions.
I remember that I paid initially 1000 satoshi for olympus server tokens - so was waiting for the app to prompt me for a new payment around 50 tx mark. This have not happened and in fact it still displays 42 tokens available in list of olympus servers. I suspect there is some bug in the counting tx logic.

**Comment by btcontract** [comment]
Everything seems to be fine. Olympus does not work as watchtower yet and only requires a token in two cases:

- when a new channel is open, to store it's encrypted backup
- when a channel is closed uncooperatively, to store delayed refunding transactions (in case if you lose a phone or delete an app before the delay is cleared).

Instead of relying on watchtowers wallet currently sets a remote peer delay period to 2000 blocks (current maximum) and sends a system notification if it has not been opened for 10 days with channels present which had an incoming payments.

Once Olympus becomes a watchtower it won't be one token per payment either but rather one token per 10 payments (this is the current plan).
