### ISSUE TITLE
Unable to receive LN payment

### ISSUE THREAD

**Issue by deafboy** [btcontract/lnwallet#6]
It says "Can't ask for payments right now because a funding Bitcoin transaction has not got 6 confirmations yet", although when I go back to a bitcoin wallet i see it has 232 confirmations.

The channel I have works fine for outgoing payments.

**Comment by btcontract** [comment]
What's your peer ID? This can be seen at "app menu" -> "channel info" and then copy text.

In general, lnwallet opens a non-public channel and expects a special message from peer once 6 confirmations pass. Once got this message lnwallet can issue payment requests. But the trick is this non-public channel stuff is rather new and there is a lot of old nodes on a network who don't know they have to send that message. Knowing your peer's ID will help me find out if that's the case.

**Comment by deafboy** [comment]
> cloudy
> 40.114.146.211
> 
> Your node ID
> 03cafcecec780f4f8d56c3e7f1ed1cd51744708fadca6fc56b883a43308f5cfa32
> 
> Peer node ID
> 022e3aa351577e6b8d181c97d9cad791f20eb34e7eef77e8be6da232589f91790c
> 
> Channel ID
> ed0535e31474af03ef8d76f2ed4ff45f6c6b063a34e414c4b7bb77bdeca22158

Cloudy is my other node. It's running eclair but I haven't updated it in a while because the build from master branch is failing.

**Comment by btcontract** [comment]
oh I know this one, people have been complaining already :) Yes, it's an outdated node and it does not know it has to send that special message.

**Comment by deafboy** [comment]
I'll try to update it. Sorry for the troubles.

**Comment by btcontract** [comment]
Actually I'll change an error message from "6 blocks..." to something like "your peer is to blame" if commit tx has 6 confirmations and there's still no message.

**Comment by irekzielinski** [comment]
I have a channel with BitRefill and get the same issue - Im willing to contact them to ask to update the node (but as far I know they are running recent version of LND) 

@btcontract - can you confirm that LND 0.4.2 should allow sending?

**Comment by btcontract** [comment]
@irekzielinski LND 0.4.2 can fulfill payment requests with routing hints included. These are the ones my wallet issues.

**Comment by btcontract** [comment]
@irekzielinski just realized you were asking a different question. I don't know if LND 0.4.2 sends `ChannelUpdate`s for non-public channels, haven't got a chance to try it yet because my wallet won't even connect to LND nodes due to their lack of data-loss-rotection support.

**Comment by urza** [comment]
Hello, I seem to have the same issue on testnet wallet with node 
LightningGemTest (
https://testnet.lightninggem.com )

**Comment by urza** [comment]
I now have 3 channels open in testnet wallet and still can't receive lightning payments. One of the channels is to 192.210.203.16 called Bitcoin+Lightning Node, is it your node? It was first on the list of nodes..

**Comment by btcontract** [comment]
@urza yes, it's mine. 

Can you provide more details, how exactly does the wallet fail to receive LN payments, are there any messages? 

In general. there are some additional conditions for receiving: http://lightning-wallet.com/using-lightning-wallet#receiving-lightning-funds

**Comment by urza** [comment]
I opened the wallet now and the message changed. Yesterday it was "Can't ask for payments right now because a funding Bitcoin transaction has not got 6 confirmations yet" - I don't know why it changed overnight as I would swear I had enough confirmations on your channel, but I might be wrong.
Today the message says in order to ask for LN payments I first need to spend some amount (0.0003..). But I did spend a little bit over that (0.0004) and it still says the same. I spent them on LightningGem Testnet and that is where I would also like to receive from. Possibly the wallet is confused because I didn't spent from the other channels?

**Comment by btcontract** [comment]
a few things are happening here at once.

First, it's true that you should be able to receive payments through `lightning gem` channel by now but their peer runs LND which still does not enable receiving (for private channels like those BLW creates receiving should be explicitly initiated by peer when they send out a special `ChannelUpdte` message, LND does not do that yet).

That's why you've seen that "no 6 confirmations yet" message yesterday even though a funding tx for `lightining gem` had 6 confirmations already. That was my wallet's fault as currently it naively thinks that once 6 confirmations are there a peer will always send a `ChannelUpdte` so if no message is present then there are no 6 confirmations yet. I'll fix that in an upcoming update.

And currently when showing that "I first need to spend some amount (0.0003..)" a wallet speaks about `Bitcoin + Lighting` channel, not `lightning gem` channel. Try to spend that `0.0003` to https://starblocks.acinq.co/ and that should finally enable receiving through `Bitcoin + Lighting`.

Admittedly, this is extremely confusing and I should better work handling all of that on UI. 

Another note: `Bitcoin + Lighting` is intentionally malicious node, it will break a channel and attempt to steal your funds if you try to send or receive more than `50 000 sat` in one payment. BLW correctly reacts in both these cases, just don't be surprised if that happens.

**Comment by urza** [comment]
Thanks for explanation.

However even after buying coffees worth of 0.0037 btc (lot's of blockachinos) still wallet says I need to spend 0.0003 first in order to receive ln payment.

**Comment by Perlover** [comment]
Hi, I have same problem
Testnet, funding transaction had 24 confirmation but I cannot receive. The remote LN node is lnd (fresh commit - right before holidays)

**Comment by Perlover** [comment]
Screenshots of problem are here:

https://www.dropbox.com/sh/50qim3xozu648bz/AAAEUBU7exP5TPN1qwv1hHw1a?dl=0

**Comment by btcontract** [comment]
It's a well known issue with LND: https://github.com/lightningnetwork/lnd/issues/1347

Basically, since BLW opens a private channel, it requires a special message from peer which enables receiving. This message is sent once a funding on-chain transaction reaches at least 6 confirmations.

Older LND versions won't send this mesage at all and for new ones BLW has to be online at the moment of funding tx reaching 6 confirmations, or else BLW won't re-send a special message at a later time. This will be fixed soon.

**Comment by btcontract** [comment]
Closing this one as a special message has been added a long time ago.
