### ISSUE TITLE
Dyndns lightning node appears offline after ip change

### ISSUE THREAD

**Issue by menzels** [btcontract/lnwallet#66]
My lighting node (LND) is behind a dyndns with changing IP addresses. I connected to the node by entering the dyndns hostname. After a day, as my IP address changed it only shows up as offline. 
When i scan the qr again to make a channel it shows as online again.

**Comment by btcontract** [comment]
As of now BLW uses a `java.net.InetSocketAddress` which resolves a domain name only once so hiding a dynamic IP behind a domain name won't work. I'll investigate if anything can be done to fix this.

**Comment by btcontract** [comment]
Just curious: can you try to hard reset a phone and open an app again, does an offline channel start working after that?

**Comment by menzels** [comment]
still offline after hard reboot (press on button >10 sec. i can not remove the battery from my phone)

**Comment by btcontract** [comment]
can you give me a current node URI? I'll connect to it and try various approaches once it becomes offline.

**Comment by menzels** [comment]
sure, it is `023a3311d6a1680b51ae7fe0d2298999ae1323db6aea9e13eed9a1ab46c8daf282@broemelbude.hopto.org:9735`
the ip will change every night (Europe timezone) i can also do manual ip changes this evening

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/49f305675100d0b2dbdba359ad9038b73f91330d

**Comment by csh59** [comment]
Unfortunately, I cannot confirm the solution of the issue since I installed the latest version from the google store v0.2-76. 
The previous version was working fine with dynamic ip nodes. Now, my android  lightning wallet channel is in endless sleeping mode when the node ip has been changed for the first time after opening a new channel. The channel viewer confirms the issue by showing always the initial ip during the opening, so there is no connection  possible then. 
To verify the proper ip announcement of my dynamic node "csh28", I checked 1ml.com and the ip was always equal to my routers WAN ip.

**Comment by btcontract** [comment]
@csh59 I'll check this ASAP, please don't close a channel meanwhile so it could be checked if this fas fixed later.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/olympus/commit/50b87d44c1c6ee828c44b909570182e3b9ef3a81, peer should appear online now in about 30 seconds after an app launch. @csh59 can you please confirm this is the case?

**Comment by csh59** [comment]
YESSS, its working now! Well done. Thank you very much!
