### ISSUE TITLE
Opening channel

### ISSUE THREAD

**Issue by mr-highball** [btcontract/lnwallet#72]
I've seen some discrepancies from various sources about channels being opened with lnwallet (incoming).
Just for clarification, is it possible for someone to open a channel to my local node? I've seen the channel details which contains useful information, but in order for someone to connect I believe an ip address is required? (Which would be difficult for constantly changing phone ip's)
My initial thought would be pubkey + Olympus server ip, but I don't know enough about the inner workings of LN and your wallet yet (and dont have anyone to test with)

**Comment by btcontract** [comment]
As of now it's not possible to open an incoming channel to BLW simply because it does not have a code to handle this case yet. Another problem is often mobile phones, especially those using cellular data, can't be directly reached due to firewalls.

Olympus is also of no help here since it's mainly a backup server which does not establish any persistent connection to a device.

The only case where this could work is when an app is already connected to some peer, perhaps because of an outgoing channel it has created earlier, in this case peer can establish an incoming channel and it is in my plans to support that as it's useful for "will-open-channel-back" strategy.

**Comment by mr-highball** [comment]
Understood. Thank you for your thorough response, it clears up a lot. I'll close this issue.
