### ISSUE TITLE
Question "Payment request valid for 2 days. Do not reuse this QR code"

### ISSUE THREAD

**Issue by rdymac** [btcontract/lnwallet#88]
Why does the app says in the receive through Lightning payment request: "Payment request valid for 2 days. Do not reuse this QR code", but the payment request seems to be valid and not expired when scanned with Eclair.

I haven't tried myself sending to it from Eclair, I wanted to check with you @btcontract what would happen.

But I tweeted the QR code here https://twitter.com/btcven/status/1034566678762479622 , so I need clarification on this limitation.

**Comment by btcontract** [comment]
Sorry for late response.

Here is how this works: "Payment request valid for 2 days" is just a recommendation. Most LN implementations including my wallet will refuse to pay to an expired invoice but technically it may be valid forever (as long as payee has a related preimage which it can hand out and thus accept a payment) but many LN implementations, such as Eclair, indeed remove their preimages once request expiration is due so technically you won't be able to fulfill it once expired. 

This is not the case with BLW but expiry recommendation is still there, the rationale is that once two days pass and it is still not paid, maybe payer is not interested in paying that invoice anymore and you're just better off with issuing a new one.

"Do not reuse this QR code" is more serious, LN payment request should not ever be reused, pasting it in public places to expect multiple payments should not ever be tried. The reason is that once an invoice is fulfilled for the first time, a payment preimage is revealed and potentially the whole world knows it, so on subsequent payment attempt a routing node may "fulfill" this payment without actually delivering it to a payee.

**Comment by btcontract** [comment]
Closing this for now, feel free to reopen if any questions left.
