### ISSUE TITLE
Lightning payment still in progress, expires in 440 blocks...

### ISSUE THREAD

**Issue by iljah** [btcontract/lnwallet#94]
Tried to send a lightning payment through CoinGate and title says what it looks like after almost 1 h. Has the payment failed and now I have to wait 3 days before I can try to send those funds again? Did lnwallet choose such a long time before payment expires or did someone else, and can I prevent this from happening again with another transfer?

**Comment by btcontract** [comment]
> Has the payment failed and now I have to wait 3 days before I can try to send those funds again?

It's not failed yet, technically it is in-flight and may be failed or fulfilled at any moment. Such delays are still common on network, the reason for them happening is one of the nodes along a payment route has accepted a payment and does nothing now, probably due to a bug.

> Did lnwallet choose such a long time before payment expires or did someone else

Yes, a most economical/short route is selected by wallet, 440 blocks implies a 3-4 hop route.

> and can I prevent this from happening again with another transfer?

Unfortunately, no. This is a fundamental aspect of LN payments. Any node along a payment route may fail this way and it's not even possible to say which exact node is doing this except if "blocks left" gets below 144, in that case it's definitely your direct peer to blame (which is CoinGate).

Please let me know if payment gets to a point where it has less than 144 blocks left, I'll try to contact CoinGate and report a bug then.

**Comment by iljah** [comment]
Thanks, it went below 144 blocks now and is still pending.

**Comment by iljah** [comment]
lnbc1m1pdmyzvypp5um2spq6n2rm94yg6qa8gjlf89gxqr5xu5zdnz9xaq44dy4sl65nqdr2d3hzqurp09kk2mn5ypnx7unhv9exgetyyp6x7wnzvvchzdmc09u8gaes09mhs6n9wyurjemc0f3nxvrxd4e8g7rx0pc82cfs8puksen9d5xqrrss4l0rlnn9s5zcvgjvdas4tae8gsdguah6lzj3kym9vd4nqv8f6729vexvg88n06h0h4vm8k707q3vvtv3j0deetjyt0fayfjm5e69z4gpkasnej

**Comment by iljah** [comment]
Thanks for looking into this. Coingate was only relaying the lightning payment so I don't think coingate order id is applicable in this case. And no funds were lost so it's not a big problem anyway. It just took a few days until the payment expired and funds were available for use again...

**Comment by btcontract** [comment]
@iljah as far as I understand you force-closed a channel at some point and https://github.com/btcontract/lnwallet/issues/96 is what happened after?

**Comment by iljah** [comment]
Yes, the frozen payment probably resulted from closing a channel that 
was relaying the payment.
