### ISSUE TITLE
payments expired, stuck

### ISSUE THREAD

**Issue by patmillertime** [btcontract/lnwallet#99]
I am trying to figure out what to do.  I have payments that are expired, stuck.  There is no way to force-close the channel, and the wallet warns me that I should wait for them to fail or be fulfilled before closing the channel.  In the past, the payments have just failed.  

![payments-stuck-3](https://user-images.githubusercontent.com/9270876/47402132-f5ddfe00-d6f8-11e8-92e8-e816bc98cebc.jpg)
![payments-stuck2](https://user-images.githubusercontent.com/9270876/47402194-33db2200-d6f9-11e8-95d3-abc382be5731.jpg)
![payments-stuck](https://user-images.githubusercontent.com/9270876/47402134-f5ddfe00-d6f8-11e8-9826-1bf04aad7569.jpg)

**Comment by btcontract** [comment]
Force-close is possible, here's how it works:

If you tap OK then channel will enter SHUTDOWN mode: it will be waiting for stuck payments to resolve before closing cooperatively.

If, while in SHUTDOWN you close a channel again, then an uncooperative closing will happen right away, you'll also see another warning before that.

But, before doing it, we have a chance to contact a peer and let them sort this out without force-closing since it's clearly s bug on their side.

If you'd like to go that way first, please let me know who is your peer and I'll try to bring a node operator here (if they are publicly known).

**Comment by patmillertime** [comment]
Thanks for your help.  The peer is ACINQ

Funding transaction: 

https://www.smartbit.com.au/tx/58248fda00660e145be66b4d2d1a334879053d33928077c11127574dec132271

Payment hashes:

lnbc7840n1pdujv2qpp54da0327759dy7sh5fw3j8ax67xwkult93dsrf3gsy8grdd0qgresdpv296kjcmtyp5kuan0d93k2grxdaezqfps9ccr2gz42dzqcqzyslu2qhdvyqarluf4hwmpsqm0rtgg7zk2mspxehv0m7ndz0q2dj3ys68ycxkvefwkq0j9yd3hvcz29jhqvk4x9perr0g7v9543clz3mugq93nw8p

lnbc4574706860p1pdusw38pp5cgj3g4j48pkxfcpyr74epdtm8a3e9tnk7svrsy7qm25wxy5x0fmsdxyf38ygmrfvejn5gpj8yhrswpq24f5ggrxdaezqnrfva58gmnfdenjq3twv9kk2mpq2p5kugrcyqcjcgz5dus9g6r9ypxk7mmwypzkuctdv4kzq5rfdcs8sgp3ypskuepq2fjkx6mvv4ehxgzrv9kjqsm0wejhygzxdaezq5rjd9mxzcmeyqkjqsnvv93kkgrcyqcscqp294va5mhlzy9mpta602knqvyecmp2jh697guw87y4s2uvesfja4z4jt7u3dlr86dp2umyywlg9a8udmaye9fcad065p9w77v9ek30h8gprhzp27

**Comment by btcontract** [comment]
Thanks, yes please keep a channel open for now, I think we'll get to the bottom of it soon enough.

**Comment by pm47** [comment]
@patmillertime if you restart your app pending payments should now be failed.

**Comment by patmillertime** [comment]
Thank you, the pending payments now show as failed.  I appreciate your prompt assistance @pm47 @btcontract
